#!/usr/bin/env python3
"""
Static checks for the seams this migration keeps breaking.

Each check exists because a CI round was spent on the bug it now catches:

  A  a type from a library the app no longer has, still named in an app
     declaration (LatGlyph vs ImageVector -- 13 errors)
  B  BuildConfig fields read by the app but not generated by the build script
     (12 errors)
  C  a type slot without a line height -- the unit test for it only runs in CI,
     this runs here (1 failing test)
  D  constants read off a third-party class that the pinned version may not have
     (3 errors)
  E  compat icon names used by the app but absent from M3Icons
  F  R.string names with no entry in the default strings.xml

Run from anywhere:  python3 tools/check-app-wiring.py
"""
import os, pathlib, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "app/src")
LIB = os.path.join(ROOT, "lattice/src/main/kotlin/dev/lattice/ui")
failures = []


def kt(root):
    for base, _, files in os.walk(root):
        for f in files:
            if f.endswith(".kt"):
                p = os.path.join(base, f)
                yield p, open(p, encoding="utf-8").read()


def rel(p):
    return os.path.relpath(p, ROOT)


def fail(check, path, line, msg):
    failures.append("%s  %s:%d  %s" % (check, rel(path), line, msg))


def lineno(src, idx):
    return src[:idx].count("\n") + 1


# ---------------------------------------------------------------- A
# Types the app cannot produce any more. ImageVector still resolves (ui-graphics
# is on the classpath) so the compiler reports a mismatch, not a missing import,
# and a grep for "material" does not find it.
FOREIGN = [
    (r'\bImageVector\b', "ImageVector: the app draws marks with dev.lattice.ui.graphic.LatGlyph"),
    (r'androidx\.compose\.material', "androidx.compose.material* is not a dependency of this module"),
    (r'\bIcons\.(Filled|Outlined|Rounded|Default)\.', None),  # allowed: compat provides them
]
icons_used = set()
for path, src in kt(APP):
    for m in re.finditer(r'\bIcons\.(?:Filled|Outlined|Rounded|Default)\.([A-Za-z0-9_]+)', src):
        icons_used.add(m.group(1))
    for pattern, msg in FOREIGN:
        if msg is None:
            continue
        for m in re.finditer(pattern, src):
            fail("A", path, lineno(src, m.start()), msg)

# ---------------------------------------------------------------- B
STANDARD = {"VERSION_NAME", "VERSION_CODE", "APPLICATION_ID", "BUILD_TYPE", "DEBUG"}
gradle_path = os.path.join(ROOT, "app/build.gradle.kts")
gradle = open(gradle_path, encoding="utf-8").read()
enabled = re.search(r'buildConfig\s*=\s*true', gradle) is not None
declared = set(re.findall(r'buildConfigField\(\s*"[A-Za-z]+"\s*,\s*"([A-Za-z0-9_]+)"', gradle))
for path, src in kt(APP):
    for m in re.finditer(r'\bBuildConfig\.([A-Za-z0-9_]+)', src):
        name = m.group(1)
        if not enabled:
            fail("B", path, lineno(src, m.start()), "BuildConfig.%s read, but buildFeatures.buildConfig is not true" % name)
        elif name not in STANDARD and name not in declared:
            fail("B", path, lineno(src, m.start()), "BuildConfig.%s is neither generated by AGP nor declared with buildConfigField" % name)

# ---------------------------------------------------------------- C
type_kt = os.path.join(LIB, "token/Type.kt")
src = open(type_kt, encoding="utf-8").read()
slots = 0
for m in re.finditer(r'val\s+([A-Za-z]+):\s*TextStyle\s*=\s*TextStyle\(', src):
    name = m.group(1)
    i = src.index("(", m.end() - 1)
    depth, j = 0, i
    while j < len(src):
        if src[j] == "(":
            depth += 1
        elif src[j] == ")":
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = src[i + 1:j]
    slots += 1
    fs = re.search(r'fontSize\s*=\s*([0-9.]+)\.sp', body)
    lh = re.search(r'lineHeight\s*=\s*([0-9.]+)\.sp', body)
    if not fs:
        fail("C", type_kt, lineno(src, m.start()), "%s has no fontSize" % name)
    elif not lh:
        fail("C", type_kt, lineno(src, m.start()),
             "%s has no lineHeight: TextUnit.Unspecified, whose .value is NaN, so the slot leans on the font's own leading" % name)
    elif float(lh.group(1)) < float(fs.group(1)):
        fail("C", type_kt, lineno(src, m.start()),
             "%s: lineHeight %s < fontSize %s" % (name, lh.group(1), fs.group(1)))

# ---------------------------------------------------------------- D
# Constants read off a third-party class. Only these are known to exist in the
# version this module pins; anything else has to be written out or the pin moved.
KNOWN = {"PERMISSION_READ_HEALTH_DATA_IN_BACKGROUND", "PERMISSION_WRITE_EXERCISE_ROUTE"}
ver = re.search(r'androidx\.health\.connect:connect-client:([0-9a-z.\-]+)', gradle)
for path, src in kt(APP):
    for m in re.finditer(r'\bHealthPermission\.([A-Z][A-Z0-9_]+)', src):
        if m.group(1) not in KNOWN:
            fail("D", path, lineno(src, m.start()),
                 "HealthPermission.%s is not in connect-client %s" % (m.group(1), ver.group(1) if ver else "?"))

# ---------------------------------------------------------------- E
icons_kt = os.path.join(LIB, "compat/M3Icons.kt")
icons_have = set(re.findall(r'public val ([A-Za-z0-9_]+)', open(icons_kt, encoding="utf-8").read()))
for name in sorted(icons_used - icons_have):
    failures.append("E  %s  Icons.*.%s used by the app, absent from M3Icons" % (rel(icons_kt), name))

# ---------------------------------------------------------------- F
strings = open(os.path.join(ROOT, "app/src/main/res/values/strings.xml"), encoding="utf-8").read()
have = set(re.findall(r'<string name="([^"]+)"', strings)) | set(re.findall(r'<plurals name="([^"]+)"', strings)) | set(re.findall(r'<string-array name="([^"]+)"', strings))
used = set()
for path, src in kt(APP):
    for m in re.finditer(r'\bR\.string\.([A-Za-z0-9_]+)', src):
        used.add((m.group(1), path, lineno(src, m.start())))
for name, path, line in sorted(used):
    if name not in have:
        fail("F", path, line, "R.string.%s has no entry in values/strings.xml" % name)

# ---------------------------------------------------------------- G
# A Kotlin DSL build script has accessors in scope that shadow package roots:
# "java" is the JavaPluginExtension the Android plugin brings with it, so a
# qualified java.time.ZonedDateTime does not resolve and the script fails to
# configure before any source file is read. Import the type instead.
SHADOWED = ("java", "kotlin", "android", "base")
scripts = 0
for path in sorted(pathlib.Path(ROOT).rglob("*.gradle.kts")):
    if "/build/" in str(path):
        continue
    scripts += 1
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        code = line.split("//")[0]
        if code.lstrip().startswith("import "):
            continue
        for root_pkg in SHADOWED:
            for m in re.finditer(r'(?<![A-Za-z0-9_.])' + root_pkg + r'\.[a-z][A-Za-z0-9_]*\.[A-Z]', code):
                fail("G", str(path), n,
                     "qualified %s.* in a build script: %s is an extension accessor here, not the package root -- add an import"
                     % (root_pkg, root_pkg))

# ----------------------------------------------------------------
print("type slots checked: %d   icons used by app: %d   R.string names used: %d"
      % (slots, len(icons_used), len({n for n, _, _ in used})))
print("buildConfig enabled: %s   fields declared: %s   build scripts checked: %d"
      % (enabled, sorted(declared) or "none", scripts))
if failures:
    print("\nFAILURES: %d" % len(failures))
    for f in failures:
        print("  " + f)
    sys.exit(1)
print("\nFAILURES: none")
